// app/pages/report/[kind]/[slug].vue
<script setup lang="ts">
import { getReview, type ReviewRecord } from "~/lib/reviews";

const route = useRoute();
const kind = Array.isArray(route.params.kind) ? route.params.kind[0] : route.params.kind;
const slug = Array.isArray(route.params.slug) ? route.params.slug[0] : route.params.slug;
const review = kind === "daily" || kind === "weekly" ? getReview(kind, String(slug)) : null;

if (!review) {
  throw createError({ statusCode: 404, statusMessage: "未找到这份复盘" });
}

const record = review as ReviewRecord;

useSeoMeta({
  title: `${record.title} · 市场日记`,
  description: record.dateLabel,
});
</script>

<template>
  <main class="report-page">
    <header class="report-topbar">
      <NuxtLink class="brand" to="/"><span class="brand-mark">M</span><span>市场日记<small>MARKET DIARY</small></span></NuxtLink>
      <div class="topbar-actions"><ThemeToggle /><NuxtLink class="secondary-link" to="/#archives">返回归档 ←</NuxtLink></div>
    </header>

    <article class="report-surface">
      <section class="report-hero">
        <span class="eyebrow">{{ record.kind === "weekly" ? "WEEKLY REVIEW" : "DAILY REVIEW" }} / {{ record.slug }}</span>
        <h1>{{ record.title }}</h1>
        <p>{{ record.dateLabel }}</p>
      </section>
      <MarkdownDocument :markdown="record.raw" />
    </article>

    <footer>本系统仅用于个人研究与历史复盘，不构成任何投资建议。<span>市场日记 · BUILD-TIME RESEARCH SYSTEM</span></footer>
  </main>
</template>

// market-diary-web/app/report/[kind]/[slug]/page.tsx
import Link from "next/link";
import { MarkdownDocument } from "../../../components/markdown-document";
import { ThemeToggle } from "../../../components/theme-toggle";
import { getReview, reviews } from "../../../lib/reviews";

export function generateStaticParams() {
  return reviews.map((review) => ({ kind: review.kind, slug: review.slug }));
}

export default async function ReportPage({ params }: { params: Promise<{ kind: "daily" | "weekly"; slug: string }> }) {
  const { kind, slug } = await params;
  const review = getReview(kind, slug);
  if (!review) return <main className="empty-state"><h1>未找到这份复盘</h1><Link href="/">返回研究终端</Link></main>;
  return <main className="report-page"><header className="report-topbar"><Link href="/" className="brand"><span className="brand-mark">M</span><span>市场日记<small>MARKET DIARY</small></span></Link><div className="topbar-actions"><ThemeToggle /><Link href="/#archives" className="source-link">返回归档 <span>←</span></Link></div></header><article className="report-surface"><section className="report-hero"><span className="eyebrow">{review.kind === "weekly" ? "WEEKLY REVIEW" : "DAILY REVIEW"} / {review.slug}</span><h1>{review.title}</h1><p>{review.dateLabel}</p></section><MarkdownDocument markdown={review.raw} /></article><footer>本系统仅用于个人研究与历史复盘，不构成任何投资建议。</footer></main>;
}
