// app/components/Dashboard.vue
<script setup lang="ts">
import {
  changeTone,
  dailyReviews,
  findRow,
  firstTable,
  reviewRoute,
  section,
  stripMarkdown,
  tableForHeading,
  weeklyReviews,
  type ReviewRecord,
} from "~/lib/reviews";

type Asset = {
  label: string;
  market: string;
  value: string;
  change: string;
  tone: string;
  values: string[];
};

const props = defineProps<{ review: ReviewRecord }>();

function assetFrom(table: ReturnType<typeof firstTable>, name: string, label: string, market: string): Asset {
  const row = findRow(table, name);
  const current = row?.at(-2) ?? "—";
  const change = row?.at(-1) ?? "—";
  return {
    label,
    market,
    value: current,
    change,
    tone: changeTone(change),
    values: row?.slice(1, -1).filter((value) => value !== "—") ?? [],
  };
}

const aTable = computed(() => firstTable(props.review.raw, "A股"));
const hkTable = computed(() => firstTable(props.review.raw, "港股"));
const goldTable = computed(() => firstTable(props.review.raw, "黄金"));
const oilTable = computed(() => firstTable(props.review.raw, "布伦特"));

const assets = computed<Asset[]>(() => [
  assetFrom(aTable.value, "上证", "上证指数", "A 股"),
  assetFrom(hkTable.value, "恒生指数", "恒生指数", "港 股"),
  assetFrom(goldTable.value, "现货黄金", "现货黄金", "贵金属"),
  oilTable.value?.rows[0]
    ? {
        label: "布伦特原油",
        market: "大宗商品",
        value: oilTable.value.rows[0][1] ?? "—",
        change: oilTable.value.rows[0][2] ?? "—",
        tone: changeTone(oilTable.value.rows[0][2]),
        values: oilTable.value.rows[0].slice(0, 2),
      }
    : { label: "布伦特原油", market: "大宗商品", value: "—", change: "—", tone: "neutral", values: [] },
]);

const strongest = computed(() => tableForHeading(props.review.raw, "周度最强"));
const weakest = computed(() => tableForHeading(props.review.raw, "周度最惨"));
const timeline = computed(() => firstTable(props.review.raw, "关键宏观事件时间线"));
const scenarios = computed(() => firstTable(props.review.raw, "情景推演"));
const summary = computed(() => section(props.review.raw, "一句话周总结").match(/>\s*(.+)/)?.[1] ?? "本周市场复盘已归档。");

const driverCards = [
  { step: "01", tag: "外部冲击", title: "能源冲击抬升风险溢价", text: "地缘局势通过油价、通胀预期与利率路径传导，压制全球风险资产。", tone: "negative" },
  { step: "02", tag: "关键分水岭", title: "通胀数据短暂改善预期", text: "CPI、PPI 回落一度缓和紧缩担忧，但未能改变周内风险偏好转弱的方向。", tone: "neutral" },
  { step: "03", tag: "国内放大器", title: "科技流动性承压", text: "大额 IPO、杠杆出清与业绩窗口共同放大了高估值科技板块的调整。", tone: "negative" },
  { step: "04", tag: "市场结果", title: "资金转向防御与现金流", text: "高波动成长板块承压，电力、银行和油气等防御方向获得相对支撑。", tone: "positive" },
];
</script>

<template>
  <main class="app-shell">
    <header class="topbar">
      <div>
        <div class="site-brand">市场日记 · 个人研究资料库</div>
        <h1>周度研究终端</h1>
        <p class="meta-line">最新资料 {{ review.slug }} · {{ review.dateLabel }}</p>
      </div>
      <div class="topbar-actions">
        <ThemeToggle />
        <NuxtLink class="primary-link" :to="reviewRoute(review)">阅读完整周报 ↗</NuxtLink>
      </div>
    </header>

    <section class="dashboard-grid">
      <aside class="archive-rail" aria-label="复盘资料导航">
        <NuxtLink class="brand" to="/">
          <span class="brand-mark">M</span>
          <span>市场日记<small>MARKET DIARY</small></span>
        </NuxtLink>

        <nav class="section-nav" aria-label="页面章节">
          <a href="#overview"><span>01</span>市场概览</a>
          <a href="#rotation"><span>02</span>板块轮动</a>
          <a href="#drivers"><span>03</span>驱动框架</a>
          <a href="#outlook"><span>04</span>情景推演</a>
        </nav>

        <div class="archive-list" id="archives">
          <p class="rail-label">周度回顾</p>
          <NuxtLink
            v-for="item in weeklyReviews"
            :key="item.slug"
            :to="reviewRoute(item)"
            :class="{ active: item.slug === review.slug }"
          >
            <span>{{ item.slug }}</span><b>{{ item.title.replace(/^\d{4}年第\d+周\s*/, "") }}</b>
          </NuxtLink>

          <p class="rail-label daily-label">日度复盘</p>
          <NuxtLink v-for="item in dailyReviews" :key="item.slug" :to="reviewRoute(item)">
            <span>{{ item.slug }}</span><b>{{ item.title.replace(/^\d{4}年/, "") }}</b>
          </NuxtLink>
        </div>
      </aside>

      <section class="main-stage">
        <section id="overview" class="summary-grid" aria-label="最新市场摘要">
          <article class="summary-item">
            <span>最新周报</span><strong>{{ review.slug }}</strong><small>{{ review.dateLabel }}</small>
          </article>
          <article class="summary-item">
            <span>市场温度</span><strong class="tone-negative">18 / 100</strong><small>极度风险规避</small>
          </article>
          <article class="summary-item">
            <span>当前策略</span><strong>防御模式</strong><small>现金流与低波动优先</small>
          </article>
        </section>

        <article class="conclusion-card">
          <div class="conclusion-label"><i /> 本周结论</div>
          <p>{{ stripMarkdown(summary) }}</p>
          <div class="conclusion-meta"><span>数据来自本地资料库</span><span>构建时同步</span></div>
        </article>

        <section class="content-section" aria-label="跨市场表现">
          <PanelHeader eyebrow="CROSS-ASSET / WEEKLY" title="跨市场表现" />
          <div class="metrics-grid"><MetricCard v-for="asset in assets" :key="asset.label" :asset="asset" /></div>
        </section>

        <section id="rotation" class="panel rotation-panel">
          <PanelHeader eyebrow="ROTATION" title="板块强弱图谱">
            <ATag color="arcoblue" size="small">{{ review.slug }}</ATag>
          </PanelHeader>
          <div class="sector-columns">
            <div>
              <h3 class="tone-positive">相对强势</h3>
              <div v-for="row in strongest?.rows.slice(0, 6)" :key="row[0]" class="sector-row">
                <b>{{ row[0] }}</b><span>{{ row[1] }}</span><small>{{ row[2] }}</small>
              </div>
              <p v-if="!strongest" class="empty-copy">暂无结构化板块数据</p>
            </div>
            <div>
              <h3 class="tone-negative">持续承压</h3>
              <div v-for="row in weakest?.rows.slice(0, 6)" :key="row[0]" class="sector-row">
                <b>{{ row[0] }}</b><span>{{ row[1] }}</span><small>{{ row[2] }}</small>
              </div>
              <p v-if="!weakest" class="empty-copy">暂无结构化板块数据</p>
            </div>
          </div>
        </section>

        <section id="drivers" class="panel drivers-panel">
          <PanelHeader eyebrow="CAUSAL MAP" title="本周核心驱动框架">
            <ATag color="green" size="small">MACRO → LIQUIDITY → RISK</ATag>
          </PanelHeader>
          <div class="driver-grid">
            <article v-for="card in driverCards" :key="card.step" :class="`driver-card tone-${card.tone}`">
              <span class="driver-step">{{ card.step }}</span>
              <div><small>{{ card.tag }}</small><h3>{{ card.title }}</h3><p>{{ card.text }}</p></div>
            </article>
          </div>
          <NuxtLink class="source-citation" :to="reviewRoute(review)">
            引用来源：{{ review.slug }}《本周核心驱动框架》 <span>阅读原文 ↗</span>
          </NuxtLink>
        </section>

        <section id="outlook" class="panel outlook-panel">
          <PanelHeader eyebrow="FORWARD VIEW" title="下周情景推演" />
          <div class="scenario-grid">
            <article v-for="row in scenarios?.rows" :key="row[0]" :class="`scenario-card tone-${changeTone(row[0])}`">
              <span>{{ row[0] }}</span><b>{{ row[2] }}</b><p>{{ row[1] }}</p><small>{{ row[3] }}</small>
            </article>
            <p v-if="!scenarios" class="empty-copy">暂无情景数据</p>
          </div>
        </section>
      </section>

      <aside class="insight-panel" aria-label="本周趋势与事件">
        <PanelHeader eyebrow="WEEKLY SIGNAL" title="本周观察" />
        <section class="temperature-box">
          <span>风险温度</span><strong>18<small>/100</small></strong>
          <div class="temperature-scale"><i class="active" /><i /><i /><i /><i /></div>
          <p>市场处于风险规避区间，防御资产相对占优。</p>
        </section>

        <section class="signal-summary">
          <span>核心判断</span>
          <p>{{ stripMarkdown(summary) }}</p>
        </section>

        <section class="timeline-section">
          <div class="subsection-head"><h3>关键事件时间线</h3><span>MACRO CLOCK</span></div>
          <ol v-if="timeline" class="timeline">
            <li v-for="row in timeline.rows.slice(0, 8)" :key="`${row[0]}-${row[1]}`">
              <time>{{ row[0] }}</time>
              <div><b>{{ row[1] }}</b><p :class="`tone-${changeTone(row[2])}`">{{ row[2] }}</p></div>
            </li>
          </ol>
          <p v-else class="empty-copy">暂无时间线数据</p>
        </section>

        <NuxtLink class="insight-link" :to="reviewRoute(review)">查看全部研究记录 <span>→</span></NuxtLink>
      </aside>
    </section>

    <footer>本系统仅用于个人研究与历史复盘，不构成任何投资建议。<span>MARKET DIARY · BUILD-TIME RESEARCH SYSTEM</span></footer>
  </main>
</template>

// market-diary-web/app/components/dashboard.tsx
import Link from "next/link";
import type { ReactNode } from "react";
import { ThemeToggle } from "./theme-toggle";
import {
  changeTone,
  dailyReviews,
  findRow,
  firstTable,
  section,
  stripMarkdown,
  tableForHeading,
  weeklyReviews,
  type ReviewRecord,
} from "../lib/reviews";

type Asset = { label: string; market: string; value: string; change: string; tone: string; values: string[] };

function numeric(value: string) {
  const number = Number.parseFloat(value.replace(/[^\d.-]/g, ""));
  return Number.isFinite(number) ? number : 0;
}

function SparkBars({ values }: { values: string[] }) {
  const numbers = values.map(numeric).filter((value) => value > 0);
  if (!numbers.length) return <span className="spark-empty">数据待补充</span>;
  const min = Math.min(...numbers);
  const max = Math.max(...numbers);
  const range = max - min || 1;
  return <div className="spark-bars" aria-label={`本周走势：${values.join("、")}`}>{numbers.map((value, index) => <i key={index} style={{ height: `${24 + ((value - min) / range) * 76}%` }} />)}</div>;
}

function assetFrom(table: ReturnType<typeof firstTable>, name: string, label: string, market: string): Asset {
  const row = findRow(table, name);
  const current = row?.at(-2) ?? "—";
  const change = row?.at(-1) ?? "—";
  return { label, market, value: current, change, tone: changeTone(change), values: row?.slice(1, -1).filter((value) => value !== "—") ?? [] };
}

function MetricCard({ asset }: { asset: Asset }) {
  return <article className="metric-card">
    <div className="metric-top"><span>{asset.market}</span><b className={`tone-${asset.tone}`}>{asset.change}</b></div>
    <div className="metric-value">{asset.value}</div>
    <div className="metric-bottom"><strong>{asset.label}</strong><SparkBars values={asset.values} /></div>
  </article>;
}

function PanelTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action?: ReactNode }) {
  return <div className="panel-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action}</div>;
}

export function Dashboard({ review }: { review: ReviewRecord | null }) {
  if (!review) return <main className="empty-state"><p className="eyebrow">MARKET DIARY</p><h1>尚未发现市场复盘</h1><p>请将日报放入 reviews/，或将周报放入 reviews/weekly/。</p></main>;

  const aTable = firstTable(review.raw, "A股");
  const hkTable = firstTable(review.raw, "港股");
  const goldTable = firstTable(review.raw, "黄金");
  const oilTable = firstTable(review.raw, "布伦特");
  const assets = [
    assetFrom(aTable, "上证", "上证指数", "A 股"),
    assetFrom(hkTable, "恒生指数", "恒生指数", "港 股"),
    assetFrom(goldTable, "现货黄金", "现货黄金", "贵金属"),
    oilTable?.rows[0] ? { label: "布伦特原油", market: "大宗商品", value: oilTable.rows[0][1] ?? "—", change: oilTable.rows[0][2] ?? "—", tone: changeTone(oilTable.rows[0][2]), values: oilTable.rows[0].slice(0, 2) } : { label: "布伦特原油", market: "大宗商品", value: "—", change: "—", tone: "neutral", values: [] },
  ];
  const strongest = tableForHeading(review.raw, "周度最强");
  const weakest = tableForHeading(review.raw, "周度最惨");
  const timeline = firstTable(review.raw, "关键宏观事件时间线");
  const scenarios = firstTable(review.raw, "情景推演");
  const summary = section(review.raw, "一句话周总结").match(/>\s*(.+)/)?.[1] ?? "本周市场复盘已归档。";
  const driverCards = [
    { step: "01", tag: "外部冲击", title: "能源冲击抬升风险溢价", text: "地缘局势通过油价、通胀预期与利率路径传导，压制全球风险资产。", tone: "negative" },
    { step: "02", tag: "关键分水岭", title: "通胀数据短暂改善预期", text: "CPI、PPI回落一度缓和紧缩担忧，但未能改变周内风险偏好转弱的方向。", tone: "neutral" },
    { step: "03", tag: "国内放大器", title: "科技流动性承压", text: "大额IPO、杠杆出清与业绩窗口共同放大了高估值科技板块的调整。", tone: "negative" },
    { step: "04", tag: "市场结果", title: "资金转向防御与现金流", text: "高波动成长板块承压，电力、银行和油气等防御方向获得相对支撑。", tone: "positive" },
  ];

  return <main className="terminal-shell">
    <aside className="side-rail" aria-label="主要导航">
      <Link className="brand" href="/"><span className="brand-mark">M</span><span>市场日记<small>MARKET DIARY</small></span></Link>
      <nav>
        <a className="nav-item active" href="#dashboard"><span>01</span>周度驾驶舱</a>
        <a className="nav-item" href="#drivers"><span>02</span>驱动框架</a>
        <a className="nav-item" href="#outlook"><span>03</span>下周情景</a>
        <a className="nav-item" href="#archives"><span>04</span>复盘归档</a>
      </nav>
      <div className="rail-bottom"><span className="live-dot" />资料库已同步<br /><small>BUILD-TIME INDEX</small></div>
    </aside>

    <section id="dashboard" className="workspace">
      <header className="topbar"><div><span className="eyebrow">WEEKLY INTELLIGENCE / {review.slug}</span><h1>风险偏好已切换至 <em>防御模式</em></h1></div><div className="topbar-actions"><ThemeToggle /><Link className="source-link" href={`/report/weekly/${review.slug}`}>阅读完整周报 <span>↗</span></Link></div></header>

      <section className="hero-grid">
        <article className="thesis-card">
          <span className="thesis-label"><i /> 本周结论</span>
          <p>{stripMarkdown(summary)}</p>
          <div className="thesis-meta"><span>{review.dateLabel}</span><span>更新于本地资料库</span></div>
        </article>
        <article className="temperature-card"><span className="eyebrow">MARKET TEMPERATURE</span><div className="temperature-number">18<small>/100</small></div><div className="temperature-scale"><i /><i /><i /><i /><i /></div><p>极度风险规避</p></article>
      </section>

      <section aria-label="跨市场表现"><PanelTitle eyebrow="CROSS-ASSET / WEEKLY" title="跨市场表现" /><div className="metrics-grid">{assets.map((asset) => <MetricCard key={asset.label} asset={asset} />)}</div></section>

      <section className="analysis-grid">
        <article className="panel sectors-panel"><PanelTitle eyebrow="ROTATION" title="板块强弱图谱" /><div className="sector-columns"><div><h3 className="positive-heading">相对强势</h3>{strongest?.rows.slice(0, 6).map((row) => <div className="sector-row" key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><small>{row[2]}</small></div>) ?? <p>暂无结构化板块数据</p>}</div><div><h3 className="negative-heading">持续承压</h3>{weakest?.rows.slice(0, 6).map((row) => <div className="sector-row" key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><small>{row[2]}</small></div>) ?? <p>暂无结构化板块数据</p>}</div></div></article>
        <article className="panel timeline-panel"><PanelTitle eyebrow="MACRO CLOCK" title="关键事件时间线" />{timeline ? <ol className="timeline">{timeline.rows.slice(0, 8).map((row) => <li key={`${row[0]}-${row[1]}`}><time>{row[0]}</time><div><b>{row[1]}</b><p className={`tone-${changeTone(row[2])}`}>{row[2]}</p></div></li>)}</ol> : <p>暂无时间线数据</p>}</article>
      </section>

      <section id="drivers" className="drivers-panel"><PanelTitle eyebrow="CAUSAL MAP" title="本周核心驱动框架" action={<span className="data-chip">MACRO → LIQUIDITY → RISK</span>} /><p className="drivers-intro">将本周叙事压缩为可快速判断的传导链；具体数据与事件保留在原始周报中。</p><div className="driver-summary-grid">{driverCards.map((card, index) => <article className={`driver-summary-card tone-${card.tone}`} key={card.step}><span className="driver-step">{card.step}</span><div><span className="driver-tag">{card.tag}</span><h3>{card.title}</h3><p>{card.text}</p></div>{index < driverCards.length - 1 && <i className="driver-arrow">→</i>}</article>)}</div><Link className="source-citation" href={`/report/weekly/${review.slug}`}>引用来源：{review.slug}《本周核心驱动框架》 <span>阅读原文 ↗</span></Link></section>

      <section id="outlook" className="outlook-panel"><PanelTitle eyebrow="FORWARD VIEW" title="下周情景推演" /><div className="scenario-grid">{scenarios?.rows.map((row) => <article className={`scenario-card tone-${changeTone(row[0])}`} key={row[0]}><span>{row[0]}</span><b>{row[2]}</b><p>{row[1]}</p><small>{row[3]}</small></article>) ?? <p>暂无情景数据</p>}</div></section>

      <section id="archives" className="archive-panel"><PanelTitle eyebrow="ARCHIVE" title="复盘归档" /><ArchiveLinks /></section>
      <footer>本系统仅用于个人研究与历史复盘，不构成任何投资建议。<span>市场日记 · BUILD-TIME RESEARCH SYSTEM</span></footer>
    </section>
  </main>;
}

function ArchiveLinks() {
  return <div className="archive-columns"><div><h3>周度回顾</h3>{weeklyReviews.map((item) => <Link href={`/report/weekly/${item.slug}`} key={item.slug}><span>{item.slug}</span><b>{item.title.replace(/^\d{4}年第\d+周\s*/, "")}</b><i>→</i></Link>)}</div><div><h3>日度复盘</h3>{dailyReviews.map((item) => <Link href={`/report/daily/${item.slug}`} key={item.slug}><span>{item.slug}</span><b>{item.title.replace(/^\d{4}年/, "")}</b><i>→</i></Link>)}</div></div>;
}
